spring:
  application:
    name: SoftwareProjectHexashop

  security:
    user:
      name: ${APP_LOGIN_USER:admin}
      password: ${APP_LOGIN_PASSWORD:admin123}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cse_3220_SoftwareProjectHexaShop}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:change_me}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: true

  docker:
    compose:
      enabled: false

server:
  port: ${PORT:8080}

app:
  seed-demo-data: true
